# Generated by Django 5.2.6 on 2025-09-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_created_at_alter_wallet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance_reveal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_balance_reveal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
